export const appInfo = {
  name: "Perfekthub",
  description: "A social hub to connect and share moments.",
  url: process.env.APP_URL || "http://localhost:3000",
  domain: process.env.APP_DOMAIN || process.env.APP_URL || "http://localhost:3000",
  author: "Ifeanyi Okoloma",
  developer: {
    name: "Ifeanyi Okoloma",
    url: "https://ifeanyikoloma.com.ng",
  },
  owner: "Ifeanyi Okoloma",
  title: "Perfekthub - Connect and Share Moments",
  keywords: [
    "social media",
    "connect",
    "share",
    "posts",
    "community",
    "friends",
    "networking",
    "media platform",
    "online community",
    "digital sharing",
  ],
};
