// ISO 3166-1 alpha-2 codes, lowercase — matches the format NewsData.io uses
// in both its `country` request parameter and the `country` array it
// returns on each article, so a profile's country can be matched directly
// against already-ingested curated_content rows with no extra API calls.
export const COUNTRIES = [
  { code: "us", name: "United States" },
  { code: "gb", name: "United Kingdom" },
  { code: "ng", name: "Nigeria" },
  { code: "za", name: "South Africa" },
  { code: "ke", name: "Kenya" },
  { code: "gh", name: "Ghana" },
  { code: "eg", name: "Egypt" },
  { code: "ca", name: "Canada" },
  { code: "au", name: "Australia" },
  { code: "in", name: "India" },
  { code: "de", name: "Germany" },
  { code: "fr", name: "France" },
  { code: "es", name: "Spain" },
  { code: "it", name: "Italy" },
  { code: "nl", name: "Netherlands" },
  { code: "pt", name: "Portugal" },
  { code: "ie", name: "Ireland" },
  { code: "se", name: "Sweden" },
  { code: "no", name: "Norway" },
  { code: "dk", name: "Denmark" },
  { code: "pl", name: "Poland" },
  { code: "br", name: "Brazil" },
  { code: "mx", name: "Mexico" },
  { code: "ar", name: "Argentina" },
  { code: "cn", name: "China" },
  { code: "jp", name: "Japan" },
  { code: "kr", name: "South Korea" },
  { code: "sg", name: "Singapore" },
  { code: "ae", name: "United Arab Emirates" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "pk", name: "Pakistan" },
  { code: "bd", name: "Bangladesh" },
  { code: "ph", name: "Philippines" },
  { code: "id", name: "Indonesia" },
  { code: "my", name: "Malaysia" },
  { code: "tr", name: "Turkey" },
  { code: "ru", name: "Russia" },
  { code: "nz", name: "New Zealand" },
];
